version: "3.8"

services:

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 8001:8001

  graph-service:
    container_name: graph-service
    build:
      context: .
      dockerfile: GraphService/Dockerfile
    ports:
      - 5001:80
      
  edmonds-karp-service:
    container_name: edmonds-karp-service
    build:
      context: .
      dockerfile: EdmondsKarpService/Dockerfile
    ports:
      - 5002:80
          
  bfs-service:
    container_name: bfs-service
    build:
      context: .
      dockerfile: BFSService/Dockerfile
    ports:
      - 5003:80

  push-relabel-service:
    container_name: push-relabel-service
    build:
      context: .
      dockerfile: PushRelabelService/Dockerfile
    ports:
      - 5004:80