version: "3.8"

services:
  graph-service:
    build:
      context: .
      dockerfile: GraphService/Dockerfile
    networks:
      - microservices-network

      
  edmonds-karp-service:
    build:
      context: .
      dockerfile: EdmondsKarpService/Dockerfile
    networks:
      - microservices-network
          
  bfs-service:
    build:
      context: .
      dockerfile: BFSService/Dockerfile
    networks:
      - microservices-network

  push-relabel-service:
    build:
      context: .
      dockerfile: PushRelabelService/Dockerfile
    networks:
      - microservices-network
      
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - microservices-network
    ports:
      - 8001:80
     
networks:
  microservices-network: